app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    {} #assets_version: SomeVersionScheme
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# app/config/config.yml
doctrine_odm.mongodb:
    server: mongodb://localhost:27017
    default_database: livechat_%kernel.environment%
    options:
        connect: true
    metadata_cache_driver: array # array, apc, xcache, memcache
    auto_generate_hydrator_classes: true
    auto_generate_proxy_classes: true
    mappings:
      ChatBundle: ~

## Doctrine Configuration
#doctrine.dbal:
#    dbname:   xxxxxxxx
#    user:     xxxxxxxx
#    password: ~

#doctrine.orm:
#    auto_generate_proxy_classes: %kernel.debug%
#    mappings:
#        HelloBundle: ~

## Swiftmailer Configuration
swiftmailer.config:
    transport:  mail
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx
