chat_homepage:
    pattern:  /livechat
    defaults: { _controller: ChatBundle:Chat:index }

chat_load:
  pattern: /livechat/load
  defaults: { _controller: ChatBundle:Chat:load }

chat_done:
  pattern: /livechat/done
  defaults: { _controller: ChatBundle:Chat:done }

chat_send:
  pattern: /livechat/send
  defaults: { _controller: ChatBundle:Chat:send }
  requirements: { _method: post }

chat_messages:
  pattern: /livechat/messages
  defaults: { _controller: ChatBundle:Chat:messages }
  requirements: { _method: get }