# -- Live Chat -----------------------------------------------------------------

sglc_chat_homepage:
    pattern:  /sglivechat
    defaults: { _controller: ChatBundle:Chat:index }

sglc_chat_load:
  pattern: /sglivechat/load
  defaults: { _controller: ChatBundle:Chat:load }

sglc_chat_accept:
  pattern: /sglivechat/accept/{id}
  defaults: { _controller: ChatBundle:Chat:accept }

sglc_chat_reject:
  pattern: /sglivechat/reject/{id}
  defaults: { _controller: ChatBundle:Chat:reject }

sglc_chat_done:
  pattern: /sglivechat/done
  defaults: { _controller: ChatBundle:Chat:done }

sglc_chat_send:
  pattern: /sglivechat/send
  defaults: { _controller: ChatBundle:Chat:send }
  requirements: { _method: post }

sglc_chat_messages:
  pattern: /sglivechat/messages.{_format}
  defaults: { _controller: ChatBundle:Chat:messages, _format: html }
  requirements: { _method: get }
  
sglc_chat_status:
  pattern: /sglivechat/status
  defaults: { _controller: ChatBundle:Chat:status }
  requirements: { _method: get }


# -- Tracker -------------------------------------------------------------------

sglc_track_index:
  pattern: /js/sglivechat-tracker
  defaults: { _controller: ChatBundle:Track:index }
  requirements: { _method: get }

sglc_track_updater:
  pattern: /js/sglivechat-tracker/update
  defaults: { _controller: ChatBundle:Track:update }

sglc_track_reset:
  pattern: /js/sglivechat-tracker/reset
  defaults: { _controller: ChatBundle:Track:reset }
sglc_track_status:
  pattern: /js/sglivechat-tracker/status.{_format}
  defaults: { _controller: ChatBundle:Track:status, _format: html }

# -- Admin ---------------------------------------------------------------------

sglc_admin_index:
  pattern: /admin/sglivechat
  defaults: { _controller: ChatBundle:Admin:index }
  requirements: { _method: get }

sglc_admin_logout:
  pattern: /admin/sglivechat/logout
  defaults: { _controller: ChatBundle:Admin:logout }
  requirements: { _method: get }

#sglc_admin_login:
#  pattern: /admin/sglivechat/login
#  defaults: { _controller: ChatBundle:Admin:login }


#sglc_admin_check_login:
#  pattern: /admin/sglivechat/login/check
#  defaults: { _controller: ChatBundle:Admin:checkLogin }
  
_security_login:
  pattern: /admin/sglivechat/login
  defaults: { _controller: ChatBundle:Admin:login }

_security_check:
  pattern: /admin/sglivechat/login/check
  defaults: { _controller: ChatBundle:Admin:checkLogin }
  requirements: { _method: post }

sglc_admin_operator:
  pattern: /admin/sglivechat/operator
  defaults: { _controller: ChatBundle:Admin:operator }

sglc_admin_operator_departments:
  pattern: /admin/sglivechat/operator/departments
  defaults: { _controller: ChatBundle:Admin:operatorDepartments }

sglc_admin_operator_department:
  pattern: /admin/sglivechat/operator/department
  defaults: { _controller: ChatBundle:Admin:operatorDepartment }
  

sglc_admin_operator_department_edit:
  pattern: /admin/sglivechat/operator/department/{id}
  defaults: { _controller: ChatBundle:Admin:operatorDepartment }

sglc_admin_operator_edit:
  pattern: /admin/sglivechat/operator/{id}
  defaults: { _controller: ChatBundle:Admin:operator }

sglc_admin_operators:
  pattern: /admin/sglivechat/operators
  defaults: { _controller: ChatBundle:Admin:operators }

sglc_admin_console_sessions:
  pattern: /admin/sglivechat/console/sessions
  defaults: { _controller: ChatBundle:Admin:sessions }

sglc_admin_console_requested_chats:
  pattern: /admin/sglivechat/console/requested-chats.{_format}
  defaults: { _controller: ChatBundle:Admin:requestedChats, _format: html }

sglc_admin_console_current_visits:
  pattern: /admin/sglivechat/console/current-visits.{_format}
  defaults: { _controller: ChatBundle:Admin:currentVisits, _format: html }

sglc_admin_console_sessions_service:
  pattern: /admin/sglivechat/console/sessions-service.json
  defaults: { _controller: ChatBundle:Admin:sessionsService }

sglc_admin_console_close:
  pattern: /admin/sglivechat/console/close/{id}
  defaults: { _controller: ChatBundle:Admin:closeChat }